name: rag-e2e
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.9
 - azure-cli-core
 - pip
 - pip:
    - numpy==1.24.4
    - openai==1.14.1
    - python-dotenv==1.0.0
    - scikit-learn==1.3.0
    - requests==2.31.0
    - pyyaml==6.0.1
    - pandas==2.0.3
    - pypdf2==3.0.1
    - tiktoken==0.4.0
    - azure-search-documents==11.4.0b8
    - pydantic==1.10.11
    - tenacity==8.3.0
    - python-dotenv==1.0.0
    - azure-identity==1.20.0
    - httpx==0.27.2